spring:
  datasource:
    #url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    url: ${{ Postgres.DATABASE_URL }}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
