spring:
  datasource:
    #url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    url: jdbc:postgresql://crossover.proxy.rlwy.net:55897/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      format_sql: true